#include "my_stm32f103xx.h"

typedef enum {
    INPUT_ANALOG,INPUT_FLOATING,INPUT_PUPD,
    OUTPUT_GPIO_PUPD_10MHZ,OUTPUT_GPIO_PUPD_2MHZ,OUTPUT_GPIO_PUPD_50MHZ,
    OUTPUT_GPIO_ODRAIN_10MHZ,OUTPUT_GPIO_ODRAIN_2MHZ,OUTPUT_GPIO_ODRAIN_50MHZ,
    OUTPUT_ALT_PUPD_10MHZ,OUTPUT_ALT_PUPD_2MHZ,OUTPUT_ALT_PUPD_50MHZ,
    OUTPUT_ALT_ODRAIN_10MHZ,OUTPUT_ALT_ODRAIN_2MHZ,OUTPUT_ALT_ODRAIN_50MHZ
}GPIO_CONFIGURATION;

void configure_gpio( GPIO_RegDef_t *PORT, int PIN_NR, GPIO_CONFIGURATION gpio_conf);
void set_gpio_output(GPIO_RegDef_t *port, int PIN_NR, int value);
int read_gpio_input(GPIO_RegDef_t *port, int PIN_NR);


